[[ -s "$HOME/.rvm/scripts/rvm" ]]                          && . "$HOME/.rvm/scripts/rvm"
export PS1="\$(~/.rvm/bin/rvm-prompt) ~ $PS1"

alias    g="git"
alias    gpp="g pull && git push"
alias    gshave="g shave"
alias    gstash="g stash"
alias    gstatus="g status"

